version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: tourism-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tourism-network

  auth:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-auth
    command: npm run start -w app/services/auth
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/tourism-auth
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
      - EMAIL_USER=amer.assouli@gmail.com
      - EMAIL_PASS=cxlnlvijjobbaxle
    depends_on:
      - mongo
    networks:
      - tourism-network

  activities:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-activities
    command: npm run start -w app/services/activities
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/tourism-activities
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
      - UPLOADS_API_KEY=internal_upload_key_456
      - UPLOADS_SERVICE_URL=http://uploads:5007
    depends_on:
      - mongo
    networks:
      - tourism-network

  reviews:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-reviews
    command: npm run start -w app/services/reviews
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://mongo:27017/tourism-reviews
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - tourism-network

  bookings:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-bookings
    command: npm run start -w app/services/bookings
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://mongo:27017/tourism-bookings
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - tourism-network

  payments:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-payments
    command: npm run start -w app/services/payments
    environment:
      - PORT=5006
      - MONGO_URI=mongodb://mongo:27017/tourism-payments
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - tourism-network

  uploads:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-uploads
    command: npm run start -w app/services/uploads
    environment:
      - PORT=5007
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - API_KEY=internal_upload_key_456
    ports:
      - "5007:5007"
    networks:
      - tourism-network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tourism-gateway
    command: npm run start -w app/gateway
    environment:
      - PORT=5000
      - JWT_SECRET=713541fed7e80f918170e2a1385d6068e407b9a94d76dcc65c8f679ac6658464a60163fff4ec227b119ef0cd21142cd62bc3b3f3203bc4512413afbf0decccfb
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth:5001/graphql
      - ACTIVITIES_SERVICE_URL=http://activities:5002/graphql
      - REVIEWS_SERVICE_URL=http://reviews:5004/graphql
      - BOOKINGS_SERVICE_URL=http://bookings:5005/graphql
      - PAYMENTS_SERVICE_URL=http://payments:5006/graphql
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - activities
      - reviews
      - bookings
      - payments
    networks:
      - tourism-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tourism-frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - tourism-network

volumes:
  mongo-data:

networks:
  tourism-network:
    driver: bridge
